apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentscript.fullname" . }}
  labels:
    {{- include "agentscript.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "agentscript.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentscript.fullname" . }}-headless
  labels:
    {{- include "agentscript.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agentscript.selectorLabels" . | nindent 4 }}
